"""Script name: fancy_schema.py. Verify real agent calls with nested tool schemas."""

import asyncio
import os
import random
import sys
from pathlib import Path
from typing import Literal
from uuid import uuid4

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from dotenv import load_dotenv
from pydantic import BaseModel, ConfigDict, Field

from dynamic_agent_client import AgentOperator, DynamicAgentClient, ToolExecutionEvent, agent_tool
from dynamic_agent_client.service_handler import ServiceHandler


class SearchFilter(BaseModel):
    """Describe constrained fields that the model must supply correctly."""

    model_config = ConfigDict(extra="forbid", strict=True)

    # Required enum and nullable fields.
    category: Literal["article", "video"]
    owner: str | None
    # Optional typed dictionary and constrained integer.
    scores: dict[str, float] = Field(default_factory=dict)
    limit: int = Field(default=10, ge=1)


class FancySchemaOperator(AgentOperator):
    """Record real tool arguments and return unpredictable execution receipts."""

    def __init__(self):
        """Track tool executions independently of the agent's final answer."""
        self.calls = []
        super().__init__()

    @agent_tool(description="Inspect basic values and return an execution receipt")
    async def basic(self, metadata: dict, count: int, ratio: float, enabled: bool, label: str) -> dict:
        """Record primitive values exactly as received from the agent."""
        assert type(metadata) is dict
        assert type(count) is int
        assert type(ratio) is float
        assert type(enabled) is bool
        assert type(label) is str
        arguments = dict(metadata=metadata, count=count, ratio=ratio, enabled=enabled, label=label)
        receipt = uuid4().hex
        self.calls.append(dict(tool="basic", arguments=arguments, receipt=receipt))
        return {"receipt": receipt}

    @agent_tool(description="Inspect nested search arguments and return an execution receipt")
    async def search(
        self,
        filters: SearchFilter,
        matrix: list[list[int]],
        groups: dict[str, list[float]],
        key: str | int,
        mode: Literal["fast", "thorough"] = "fast",
        note: str | None = None,
    ) -> dict:
        """Validate and record nested values generated by the agent.

        :param filters: Structured search filters.
        :param matrix: Rows of integer values.
        :param groups: Named groups of numeric scores.
        """
        # Schema generation leaves JSON objects as dictionaries at execution time.
        assert type(filters) is dict
        validated = SearchFilter.model_validate(filters)
        assert type(matrix) is list and all(type(row) is list for row in matrix)
        assert all(type(value) is int for row in matrix for value in row)
        assert type(groups) is dict and all(type(values) is list for values in groups.values())
        assert all(type(value) in (int, float) for values in groups.values() for value in values)
        assert type(key) in (str, int)
        assert mode in ("fast", "thorough")
        assert note is None or type(note) is str
        arguments = dict(filters=validated.model_dump(), matrix=matrix, groups=groups, key=key, mode=mode, note=note)
        receipt = uuid4().hex
        self.calls.append(dict(tool="search", arguments=arguments, receipt=receipt))
        return {"receipt": receipt, "row_sums": [sum(row) for row in matrix]}


async def run_case(client, operator, tool, request, expected):
    """Require a successful real tool call with correct values and a used result."""
    events = []
    before = len(operator.calls)
    response = await asyncio.wait_for(client.trigger(request, on_event=events.append), 120)
    print(f"{tool} response: {response}", flush=True)
    executions = operator.calls[before:]
    assert executions, f"Agent did not execute {tool}"
    assert all(call["tool"] == tool and call["arguments"] == expected for call in executions), executions
    tool_events = [event for event in events if isinstance(event, ToolExecutionEvent)]
    assert not any(event.status == "failed" for event in tool_events), tool_events
    assert any(event.name == f"FancySchemaOperator_{tool}" and event.status == "succeeded" for event in tool_events)
    assert any(call["receipt"] in response for call in executions), "Agent did not use the tool's actual result"
    print(f"{tool.upper()} SCHEMA CALL PASSED", flush=True)


async def main():
    """Run live schema cases in a fresh session and remove its messages afterward."""
    load_dotenv()
    client = None
    await DynamicAgentClient.connect(f"http://localhost:{os.getenv('PORT', '7777')}")
    try:
        client = await DynamicAgentClient.create(
            setting="Use the requested tool with the supplied values. Return its exact execution receipt in your final answer.",
            session_id="smoke-fancy-schema-" + uuid4().hex[:8],
        )
        operator = FancySchemaOperator()
        await client.add_operator(operator)

        # Vary the input so the tool result cannot be a canned response.
        count = random.randint(2, 20)
        label = "probe-" + uuid4().hex[:8]
        expected = dict(metadata={"source": label}, count=count, ratio=0.75, enabled=True, label=label)
        await run_case(client, operator, "basic",
            f"Call basic: metadata has source '{label}', count is {count}, ratio is 0.75, enabled is true, and label is '{label}'.",
            expected)

        matrix = [[count, 2], [3, 4]]
        expected = dict(filters=dict(category="article", owner=None, scores={"quality": 0.75}, limit=3),
            matrix=matrix, groups={"alpha": [0.25, 0.5]}, key=count, mode="thorough", note=None)
        await run_case(client, operator, "search",
            f"Call search with article filters: owner null, quality score 0.75, limit 3. "
            f"Matrix rows are [{count}, 2] and [3, 4]. Groups has alpha scores 0.25 and 0.5. "
            f"Use integer key {count}, thorough mode, and null note.", expected)

        # Exercise the other union branch and omitted defaults in another turn.
        expected = dict(filters=dict(category="video", owner="Ada", scores={}, limit=10),
            matrix=[[1]], groups={}, key=label, mode="fast", note=None)
        await run_case(client, operator, "search",
            f"Call search for category video with owner Ada. Use matrix [[1]], empty groups, and string key '{label}'. "
            "Omit scores, limit, mode, and note to use their defaults.", expected)
        print("ALL FANCY SCHEMA SMOKES PASSED", flush=True)
    finally:
        try:
            if client is not None:
                session_id = client.session_id
                try:
                    await asyncio.wait_for(client.stop(), 10)
                finally:
                    await client.close()
                    await DynamicAgentClient.delete_session(session_id)
        finally:
            await ServiceHandler.stop()


if __name__ == "__main__":
    asyncio.run(main())
