"""
Knowledge node accessor for Milvus.

Schema: bucket_{bucket_name} (one collection per bucket)
├── id              (VARCHAR, primary key) — blueprint_instance.id from PG
├── instance_id     (VARCHAR)              — groups entities from same ingestion
├── value           (VARCHAR)              — the raw attribute text chunk
├── sparse_vector   (SPARSE_FLOAT_VECTOR)  — BM25 sparse vector (auto-generated from value)
├── embedding       (FLOAT_VECTOR)         — dense vector of value only
"""
from pymilvus import DataType, Function, FunctionType
from dynamic_agent_service.data.data_accessor import DataAccessor
from dynamic_agent_service.external_service.knowledge_engine import KnowledgeEngine
from dynamic_agent_service.external_service.milvus_instance import MilvusInstance


def _collection_name(bucket_name: str) -> str:
    return f"bucket_{bucket_name.replace('-', '_')}"


class KnowledgeNodeAccessor(DataAccessor):

    @classmethod
    async def ensure_tables_exist(cls, bucket_name: str) -> bool:
        collection_name = _collection_name(bucket_name)
        dimension = KnowledgeEngine.get_dimension()
        client = MilvusInstance.get_client()
        if client.has_collection(collection_name):
            return True

        schema = client.create_schema(auto_id=False, enable_dynamic_field=False)
        schema.add_field("id", DataType.VARCHAR, is_primary=True, max_length=64)
        schema.add_field("instance_id", DataType.VARCHAR, max_length=64)
        schema.add_field("value", DataType.VARCHAR, max_length=65535, enable_analyzer=True)
        schema.add_field("sparse_vector", DataType.SPARSE_FLOAT_VECTOR)
        schema.add_field("embedding", DataType.FLOAT_VECTOR, dim=dimension)

        # Add BM25 function to auto-generate sparse_vector from value
        bm25_function = Function(
            name="bm25",
            function_type=FunctionType.BM25,
            input_field_names=["value"],
            output_field_names=["sparse_vector"]
        )
        schema.add_function(bm25_function)

        client.create_collection(collection_name, schema=schema)

        index_params = client.prepare_index_params()
        index_params.add_index("embedding", index_type="AUTOINDEX", metric_type="COSINE")
        index_params.add_index("sparse_vector", index_type="SPARSE_INVERTED_INDEX", metric_type="BM25")
        client.create_index(collection_name, index_params)

        client.load_collection(collection_name)
        return True

    @staticmethod
    def upsert_entities(bucket_name: str, entities: list[dict]):
        """
        Each entity dict: {"id": str, "instance_id": str, "value": str, "embedding": list[float]}
        Note: sparse_vector is auto-generated by Milvus from value field
        """
        collection_name = _collection_name(bucket_name)
        MilvusInstance.upsert(collection_name, entities)

    @staticmethod
    def search(
        bucket_name: str,
        query_embedding: list[float],
        query_text: str = "",
        top_k: int = 10,
        embedding_weight: float = 0.5,
        bm25_weight: float = 0.5,
    ) -> list[dict]:
        """
        Hybrid search combining dense vector (embedding) and sparse retrieval (BM25).

        Args:
            bucket_name: Bucket to search in
            query_embedding: Dense vector for semantic search
            query_text: Text query for BM25 keyword search
            top_k: Number of results to return
            embedding_weight: Weight for embedding similarity (0-1)
            bm25_weight: Weight for BM25 score (0-1)

        Returns:
            List of results with combined scores
        """
        collection_name = _collection_name(bucket_name)

        if query_text and bm25_weight > 0:
            # Hybrid search: embedding + BM25
            return MilvusInstance.hybrid_search(
                collection_name=collection_name,
                query_vector=query_embedding,
                query_text=query_text,
                top_k=top_k,
                embedding_weight=embedding_weight,
                bm25_weight=bm25_weight,
                output_fields=["instance_id", "value"],
            )
        else:
            # Pure embedding search
            return MilvusInstance.search(
                collection_name=collection_name,
                query_vector=query_embedding,
                top_k=top_k,
                output_fields=["instance_id", "value"],
            )

    @staticmethod
    def get_by_ids(bucket_name: str, ids: list[str]) -> list[dict]:
        collection_name = _collection_name(bucket_name)
        client = MilvusInstance.get_client()
        return client.get(
            collection_name=collection_name,
            ids=ids,
            output_fields=["instance_id", "value"],
        )

    @staticmethod
    def delete_by_ids(bucket_name: str, ids: list[str]):
        collection_name = _collection_name(bucket_name)
        MilvusInstance.delete(collection_name, ids)